language: android
#jdk: oraclejdk8

android:
  components:
    - build-tools-26.0.2
    - android-26
    - extra

env:
  - TERM=dumb

script:
  - ./gradlew build -x lint

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file:
    - app/build/outputs/apk/app-debug.apk
  skip_cleanup: true
  on:
    tags: true

#cache:
#  directories:
#    - $HOME/.m2
#    - $HOME/.gradle/wrapper/
